server:
  port: 8081	
logging:
  path: logs
  file: mylog.log	
spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456		
mybatis:
  type-aliases-package: org.mybatis.org.mybatis.model
  mapper-locations:
    - mapper/*	 		